//
// Created by Niels on 28/12/21.
//

#ifndef MERCHANTSHIPS_SHIPSTATES_H
#define MERCHANTSHIPS_SHIPSTATES_H

enum class ShipStates
{
    DEFAULT, LEAVING, ARRIVING, SAILING, COMBAT, DEAD, VICTORY
};

#endif //MERCHANTSHIPS_SHIPSTATES_H
