//
// Created by Niels on 14/12/21.
//

#ifndef MERCHANTSHIPS_HARBORSTATES_H
#define MERCHANTSHIPS_HARBORSTATES_H

enum class HarborStates
{
    GOODS, CANONS, SHIPS, LEAVING, REPAIRING, QUIT, MENU, TRADING, TRADING_SHIP
};

#endif //MERCHANTSHIPS_HARBORSTATES_H

